#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 20 14:18:36 2019

@author: gabrielcaschera
"""

'''
    Função para leitura do arquivo csv a partir do sistema de arquivos do computador
'''

def read_csv_file():
    import tkinter as tk
    from tkinter import filedialog

    root = tk.Tk()
    root.withdraw()

    file_path = filedialog.askopenfilename() 
